<a href="https://colab.research.google.com/github/iAmHira19/Support-Vector-Machine-SVM-Code/blob/main/SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import necessary libraries
import numpy as np
from sklearn import datasets  # To load the Iris dataset
from sklearn.model_selection import train_test_split  # To split the dataset into training and testing sets
from sklearn.preprocessing import StandardScaler  # To standardize the feature data
from sklearn.svm import SVC  # SVM classifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix  # To evaluate the model

# Load the Iris dataset
# The Iris dataset contains 150 samples of iris flowers, with 4 features (sepal length, sepal width, petal length, petal width) and 3 classes (species)
iris = datasets.load_iris()

# X contains the feature data, y contains the labels (the target variable)
X = iris.data
y = iris.target

# Split the dataset into training and testing sets
# train_test_split is used to split the dataset into a training set (80%) and a testing set (20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the feature data
# StandardScaler scales the data to have zero mean and unit variance, which is important for SVM as it is sensitive to the scale of the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Create an SVM classifier
# SVC stands for Support Vector Classification
# The kernel parameter specifies the kernel type to be used in the algorithm ('linear', 'poly', 'rbf', 'sigmoid')
# C is the regularization parameter; it controls the trade-off between achieving a low error on the training data and minimizing the model complexity
# gamma defines how far the influence of a single training example reaches (only for 'rbf', 'poly', and 'sigmoid')
svm = SVC(kernel='linear', C=1.0, gamma='auto')

# Train the SVM classifier on the training data
svm.fit(X_train, y_train)

# Predict the labels of the test data
y_pred = svm.predict(X_test)

# Evaluate the model
# accuracy_score calculates the proportion of correctly classified instances
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

# classification_report provides a detailed report including precision, recall, f1-score for each class
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# confusion_matrix shows the performance of the classifier in a matrix format
# Rows represent the actual classes, and columns represent the predicted classes
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))


Accuracy: 96.67%

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.89      0.94         9
           2       0.92      1.00      0.96        11

    accuracy                           0.97        30
   macro avg       0.97      0.96      0.97        30
weighted avg       0.97      0.97      0.97        30


Confusion Matrix:
[[10  0  0]
 [ 0  8  1]
 [ 0  0 11]]
